name: ci

on:
  push:
    branches:
      - main
      - develop
      - issues/*
  pull_request:
    branches:
      - main
      - develop
      - issues/*

env:
  cargo-directory: ./
  npm-directory: ./www/

jobs:
  ci:
    runs-on: ubuntu-22.04
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
    # ===== Cargo =====
    - name: Restore cargo cache
      id: cargo_bin_cache_id
      uses: actions/cache@v2
      with:
        path: ~/.cargo/bin/
        key: cargo-bin
    - name: Install Rust toolchain
      uses: dtolnay/rust-toolchain@stable
    - name: Format
      run: cargo fmt --all -- --check
      working-directory: ${{ env.cargo-directory }}
    - name: Lint
      run: cargo clippy
      working-directory: ${{ env.cargo-directory }}
    - name: Build check
      run: cargo check
      working-directory: ${{ env.cargo-directory }}
    - name: Install cargo-generate and wasm-pack
      run: cargo install cargo-generate wasm-pack
      working-directory: ${{ env.cargo-directory }}
    - name: Build
      run: wasm-pack build
      working-directory: ${{ env.cargo-directory }}
    # ===== npm =====
    - name: Setup Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '18'
    - name: Install dependencies
      run: yarn install
      working-directory: ${{ env.npm-directory }}
    - name: Lint
      run: yarn lint
      working-directory: ${{ env.npm-directory }}
    - name: Type check
      run: yarn type-check
      working-directory: ${{ env.npm-directory }}
